<?php

/**
 * @file
 * Markdown addons
 *
 * Extends the markdown syntax output filter.
 */
use Drupal\markdown_extra\Filter\MarkdownExtraAttributesFilter;

/**
 * Implements hook_filter_info()
 *
 * @return array
 */
function markdown_extra_filter_info() {
  $filters['markdown_extra'] = array(
    'title' => t('Internal path to alias filter'),
    'description' => t('Extends the markdown syntax output filter. Converting node/x path to alias.'),
    'process callback' => 'markdown_extra_filter_html',
    'cache' => FALSE,
  );
  $filters['markdown_extra_attributes'] = array(
    'title' => t('Markdown attributes filter'),
    'description' => t('Allows image classes in markdown images.'),
    'process callback' => '_markdown_extra_filter_attributes',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Process callback for 'markdown_extra' filter.
 *
 * @param string $text
 *
 * @return mixed
 */
function markdown_extra_filter_html($text) {

  // convert node/x to alias
  if (preg_match_all('/\((node\/\d+)\)/', $text, $matches)) {
    foreach ($matches[0] as $k => $v) {
      $text = str_replace($matches[0][$k], '(' . url($matches[1][$k]) . ')', $text);
    }
  }

  return $text;
}

/**
 * Process callback for 'markdown_extra_attributes' filter.
 *
 * @param string $text
 *
 * @return string
 */
function _markdown_extra_filter_attributes($text) {
  $filter = new MarkdownExtraAttributesFilter();
  return $filter->filter($text);
}
